//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I18nIt.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I18nIt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Export failed! 的本地化字符串。
        /// </summary>
        internal static string Text_Export_failed_ {
            get {
                return ResourceManager.GetString("Text_Export_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export succeed! 的本地化字符串。
        /// </summary>
        internal static string Text_Export_succeed_ {
            get {
                return ResourceManager.GetString("Text_Export_succeed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please create a translate file first. 的本地化字符串。
        /// </summary>
        internal static string Text_please_create_a_translate_file_first_ {
            get {
                return ResourceManager.GetString("Text_please_create_a_translate_file_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please open the base file and translate file first 的本地化字符串。
        /// </summary>
        internal static string text_Please_open_the_base_file_and_translate_file_first {
            get {
                return ResourceManager.GetString("text_Please_open_the_base_file_and_translate_file_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please open the base file and translated file together first. 的本地化字符串。
        /// </summary>
        internal static string Text_Please_open_the_base_file_and_translated_file_together_first_ {
            get {
                return ResourceManager.GetString("Text_Please_open_the_base_file_and_translated_file_together_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please open the base file first. 的本地化字符串。
        /// </summary>
        internal static string Text_please_open_the_base_file_first_ {
            get {
                return ResourceManager.GetString("Text_please_open_the_base_file_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The item has existed in translate file, could not be created. 的本地化字符串。
        /// </summary>
        internal static string Text_the_item_has_existed_in_translate_file__could_not_be_created_ {
            get {
                return ResourceManager.GetString("Text_the_item_has_existed_in_translate_file__could_not_be_created_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate file has existed. Can&apos;t clone base file. 的本地化字符串。
        /// </summary>
        internal static string Text_Translate_file_has_existed__Can_t_clone_base_file_ {
            get {
                return ResourceManager.GetString("Text_Translate_file_has_existed__Can_t_clone_base_file_", resourceCulture);
            }
        }
    }
}
